### PR TITLE
update package.json to reflect new name

### PR DESCRIPTION
**Pull request by ryelo**
The path needs to be `/docs/api` instead of `/docs/api-docs`

### CODE REVIEW

**Comment by karelhala** [comment]
The api-docs naming was actually intentional https://github.com/RedHatInsights/cloud-services-config/pull/19#discussion_r306298500 if @kruai is fine with this change I am good with it as well, it will be kinda pain to sync this correctly to all env though.

**Comment by ryelo** [comment]
@karelhala Yeah, I just talked to him about it. Ian wants to change it so the path doesn't have a superfluous `docs` portion in the url.

**Comment by karelhala** [comment]
> path doesn't have a superfluous docs portion in the url

That shouldn't have been necessary, this is to identify the app in navigation. The id could have remain the same and reload could have been added to config in order to change the actual URL shown in URL.

**Comment by ryelo** [comment]
Ah then let's do that instead

**Comment by karelhala** [comment]
Yeah, do that! App id change in prod apps is hard and can cause a lot of headaches for us when synching config and app envs.

**Pull request closed without merging**
